=== goGetSomeFries/alatka-messages/src/test/resources/alatka-messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://message.alatka.com" targetNamespace="http://message.alatka.com">
    <xs:element name="alatka-messages" type="alatka-messagesType"/>
    <xs:complexType name="alatka-messagesType">
        <xs:all>
            <xs:element type="xs:string" name="remark"/>
            <xs:element type="xs:string" name="type">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="iso"/>
                        <xs:enumeration value="fixed"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="group"/>
            <xs:element type="xs:string" name="code"/>
            <xs:element type="xs:string" name="domain" minOccurs="0"/>
            <xs:element type="xs:string" name="usage" minOccurs="0"/>
            <xs:element type="xs:string" name="domainType" minOccurs="0"/>
            <xs:element type="xs:string" name="charset" minOccurs="0"/>
            <xs:element type="xs:string" name="holder" minOccurs="0"/>
            <xs:element type="messageType" name="message"/>
        </xs:all>
    </xs:complexType>
    <xs:complexType name="messageType">
        <xs:sequence>
            <xs:element type="payloadType" name="header" minOccurs="0"/>
            <xs:element type="payloadType" name="request" minOccurs="0"/>
            <xs:element type="payloadType" name="response" minOccurs="0"/>
            <xs:element type="payloadType" name="payload" minOccurs="0"/>
            <xs:element type="payloadType" name="subPayload" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="payloadType">
        <xs:sequence>
            <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="fieldType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="index" use="optional"/>
                <xs:attribute type="xs:int" name="domainNo" use="required"/>
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="clazz" use="optional"/>
                <xs:attribute type="xs:string" name="pattern" use="optional"/>
                <xs:attribute type="xs:boolean" name="fixed" use="optional"/>
                <xs:attribute type="xs:int" name="length" use="required"/>
                <xs:attribute type="xs:string" name="remark" use="required"/>
                <xs:attribute type="xs:string" name="status" use="optional"/>
                <xs:attribute type="xs:string" name="pageSizeName" use="optional"/>
                <xs:attribute type="xs:string" name="parseType" use="optional"/>
                <xs:attribute type="xs:boolean" name="existSubdomain" use="optional"/>
                <xs:attribute type="xs:string" name="subdomainType" use="optional"/>
                <xs:attribute type="xs:string" name="aliasName" use="optional"/>
                <xs:attribute type="xs:int" name="maxLength" use="optional"/>
                <xs:attribute type="xs:boolean" name="nonSubdomainException" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== goGetSomeFries/alatka-messages/src/test/resources/9001.3006.fixed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="fixed" group="9001" code="3006" remark="明细查询">
        <request>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" clazz="java.lang.String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" clazz="java.lang.String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" clazz="java.lang.String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" clazz="java.lang.String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" clazz="java.lang.String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" clazz="java.lang.String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" clazz="java.lang.Integer"/>
            <field domainNo="8" name="cardNbr" length="19" remark="卡号" clazz="java.lang.String"/>
            <field domainNo="9" name="tranYM" length="4" remark="账单年月" clazz="java.time.YearMonth" pattern="yyMM"/>
            <field domainNo="10" name="option" length="1" remark="币种选项" clazz="java.lang.String"/>
            <field domainNo="11" name="rtnInd" length="1" remark="翻页标志" clazz="java.lang.String"/>
            <field domainNo="12" name="valDate" length="8" remark="入账日期" clazz="java.time.LocalDate" pattern="yyyyMMdd"/>
            <field domainNo="13" name="purDate" length="8" remark="记录日期" clazz="java.time.LocalDate" pattern="yyyyMMdd"/>
            <field domainNo="14" name="purTime" length="8" remark="消费时间" clazz="java.time.LocalTime" pattern="HHmmssSS"/>
            <field domainNo="15" name="tranNo" length="6" remark="交易流水号" clazz="java.lang.Integer"/>
            <field domainNo="16" name="pinFlag" length="1" remark="是否检查密码标志" clazz="java.lang.String"/>
            <field domainNo="17" name="pin" length="8" remark="密码" clazz="[B"/>
            <field domainNo="18" name="enqFlag" length="1" remark="查询条件" clazz="java.lang.String"/>
            <field domainNo="19" name="orderFlag" length="1" remark="显示顺序标志" clazz="java.lang.String"/>
        </request>
        <response>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" clazz="java.lang.String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" clazz="java.lang.String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" clazz="java.lang.String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" clazz="java.lang.String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" clazz="java.lang.String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" clazz="java.lang.String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" clazz="java.lang.Integer"/>
            <field domainNo="8" name="cardNbr" length="19" remark="卡号" clazz="java.lang.String"/>
            <field domainNo="9" name="tranYM" length="4" remark="账单年月" clazz="java.time.YearMonth" pattern="yyMM"/>
            <field domainNo="10" name="option" length="1" remark="币种选项" clazz="java.lang.String"/>
            <field domainNo="11" name="counts" length="2" remark="本次返回交易条数" clazz="java.lang.Integer"/>
            <field domainNo="12" name="rtnInd" length="1" remark="翻页标志" clazz="java.lang.String"/>
            <field domainNo="13" name="elements" fixed="false" length="141" remark="集合" clazz="java.util.ArrayList" pageSizeName="counts" existSubdomain="true" subdomainType="PAGE"/>
        </response>
        <subPayload domain="F13">
            <field domainNo="1" name="monthNbr" length="3" remark="月份序号" clazz="java.lang.Integer"/>
            <field domainNo="2" name="valDate" length="8" remark="入账日期" clazz="java.time.LocalDate" pattern="yyyyMMdd"/>
            <field domainNo="3" name="purDate" length="8" remark="记录日期" clazz="java.time.LocalDate" pattern="yyyyMMdd"/>
            <field domainNo="4" name="purTime" length="8" remark="消费时间" clazz="java.time.LocalTime" pattern="HHmmssSS"/>
            <field domainNo="5" name="tranNo" length="6" remark="交易流水号" clazz="java.lang.Integer"/>
            <field domainNo="6" name="tranType" length="4" remark="交易类型" clazz="java.lang.String"/>
            <field domainNo="7" name="amount" length="12" remark="交易金额" clazz="java.math.BigDecimal"/>
            <field domainNo="8" name="amountFl" length="1" remark="交易金额符号" clazz="java.lang.String"/>
            <field domainNo="9" name="authCode" length="6" remark="授权代码" clazz="java.lang.String"/>
            <field domainNo="10" name="desline1" length="42" remark="交易描述1" clazz="java.lang.String"/>
            <field domainNo="11" name="desline2" length="25" remark="交易描述2" clazz="java.lang.String"/>
            <field domainNo="12" name="cardEnd" length="4" remark="卡号后四位" clazz="java.lang.String"/>
            <field domainNo="13" name="currNum" length="3" remark="货币代码" clazz="java.lang.String"/>
            <field domainNo="14" name="mpFlag" length="1" remark="保留字段1" clazz="java.lang.String"/>
            <field domainNo="15" name="purDate1" length="4" remark="消费日期" clazz="java.time.MonthDay" pattern="MMdd"/>
            <field domainNo="16" name="revInd" length="1" remark="撤销冲正标志" clazz="java.lang.String"/>
            <field domainNo="17" name="mcc" length="4" remark="商户类别" clazz="java.lang.String"/>
            <field domainNo="18" name="facePayFlag" length="1" remark="人脸支付标志" clazz="java.lang.String"/>
        </subPayload>
    </message>
</alatka-messages>

=== goGetSomeFries/alatka-messages/src/test/resources/9001.template.fixed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="fixed" group="9001" code="template" remark="9001固定格式模板">
        <request>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" clazz="java.lang.String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" clazz="java.lang.String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" clazz="java.lang.String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" clazz="java.lang.String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" clazz="java.lang.String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" clazz="java.lang.String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" clazz="java.lang.Integer"/>
        </request>
        <response>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" clazz="java.lang.String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" clazz="java.lang.String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" clazz="java.lang.String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" clazz="java.lang.String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" clazz="java.lang.String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" clazz="java.lang.String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" clazz="java.lang.Integer"/>
        </response>
    </message>
</alatka-messages>
