=== goGetSomeFries/alatka-messages/alatka-messages-core/src/main/resources/alatka-messages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="http://messages.alatka.com" targetNamespace="http://messages.alatka.com">
    <xs:element name="alatka-messages" type="alatka-messagesType"/>
    <xs:complexType name="alatka-messagesType">
        <xs:sequence>
            <xs:element type="messageType" name="message"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="messageType">
        <xs:sequence>
            <xs:element type="payloadType" name="header" minOccurs="0"/>
            <xs:element type="payloadType" name="request" minOccurs="0"/>
            <xs:element type="payloadType" name="response" minOccurs="0"/>
            <xs:element type="payloadType" name="payload" minOccurs="0"/>
            <xs:element type="subPayloadType" name="subPayload" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="remark" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="group" use="required"/>
        <xs:attribute type="xs:string" name="code" use="required"/>
        <xs:attribute type="xs:string" name="charset" use="optional"/>
        <xs:attribute type="xs:string" name="clazz" use="optional"/>
    </xs:complexType>
    <xs:complexType name="payloadType">
        <xs:sequence>
            <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="clazz" use="optional"/>
    </xs:complexType>
    <xs:complexType name="subPayloadType">
        <xs:sequence>
            <xs:element type="fieldType" name="field" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="domain" use="required"/>
        <xs:attribute type="xs:string" name="domainType" use="optional"/>
        <xs:attribute type="xs:string" name="usage" use="optional"/>
        <xs:attribute type="xs:string" name="clazz" use="optional"/>
    </xs:complexType>
    <xs:complexType name="fieldType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:int" name="index" use="optional"/>
                <xs:attribute type="xs:string" name="domainNo" use="required"/>
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:string" name="clazz" use="optional"/>
                <xs:attribute type="xs:string" name="className" use="optional"/>
                <xs:attribute type="xs:string" name="pattern" use="optional"/>
                <xs:attribute type="xs:boolean" name="fixed" use="optional"/>
                <xs:attribute type="xs:int" name="length" use="optional"/>
                <xs:attribute type="xs:string" name="remark" use="required"/>
                <xs:attribute type="xs:string" name="status" use="optional"/>
                <xs:attribute type="xs:string" name="pageSizeName" use="optional"/>
                <xs:attribute type="xs:string" name="parseType" use="optional"/>
                <xs:attribute type="xs:string" name="lenParseType" use="optional"/>
                <xs:attribute type="xs:boolean" name="existSubdomain" use="optional"/>
                <xs:attribute type="xs:string" name="subdomainType" use="optional"/>
                <xs:attribute type="xs:string" name="aliasName" use="optional"/>
                <xs:attribute type="xs:int" name="maxLength" use="optional"/>
                <xs:attribute type="xs:boolean" name="nonSubdomainException" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== goGetSomeFries/alatka-messages/alatka-messages-core/src/test/resources/9001.template.fixed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="fixed" group="9001" code="template" remark="9001固定格式模板">
        <request>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" className="String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" className="String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" className="String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" className="String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" className="String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" className="String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" className="Integer"/>
        </request>
        <response>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" className="String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" className="String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" className="String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" className="String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" className="String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" className="String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" className="Integer"/>
        </response>
    </message>
</alatka-messages>

=== goGetSomeFries/alatka-messages/alatka-messages-core/src/test/resources/visa.common.iso.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="iso" group="visa" code="common" remark="visa 8583报文">
        <header>
            <field domainNo="1" name="messageLength" fixed="true" length="1" remark="报文长度" className="Integer" parseType="BINARY"/>
            <field domainNo="2" name="f2" fixed="true" length="1" remark="Header Flag and Format" className="String" parseType="BINARY"/>
            <field domainNo="3" name="f3" fixed="true" length="1" remark="Text Format" className="String"/>
            <field domainNo="4" name="f4" fixed="true" length="2" remark="Total Message Length" className="String"/>
            <field domainNo="5" name="f5" fixed="true" length="2" remark="Destination Station ID" className="String"/>
            <field domainNo="6" name="f6" fixed="true" length="2" remark="Source Station ID" className="String"/>
            <field domainNo="7" name="f7" fixed="true" length="1" remark="Round-Trip Control Information" className="String"/>
            <field domainNo="8" name="f8" fixed="true" length="2" remark="V.I.P. Flags" className="String"/>
            <field domainNo="9" name="f9" fixed="true" length="2" remark="Message Status Flags" className="String"/>
            <field domainNo="10" name="f10" fixed="true" length="1" remark="Batch Number" className="String"/>
            <field domainNo="11" name="f11" fixed="true" length="2" remark="Reserved" className="String"/>
            <field domainNo="12" name="f12" fixed="true" length="1" remark="User Information" className="String"/>
            <field domainNo="13" name="f13" fixed="true" length="2" remark="Bitmap" className="BitMap" parseType="BINARY" pattern="13"/>
            <field domainNo="14" name="f14" fixed="true" length="2" remark="Bitmap, Reject Data Group" className="Integer" parseType="BCD"/>
        </header>
        <payload>
            <field domainNo="0" name="messageType" fixed="true" length="4" remark="报文类型" className="String" parseType="EBCDIC"/>
            <field domainNo="1" name="bitMap" fixed="false" length="16" remark="位图" className="BitMap" parseType="BINARY"/>
            <field domainNo="2" name="pan" fixed="false" length="1" maxLength="10" remark="主账号" className="String" parseType="BCD" lenParseType="BINARY"/>
            <field domainNo="63" name="f63" fixed="false" length="1" maxLength="255" remark="VIP Private-Use Fields" existSubdomain="true" subdomainType="BITMAP" lenParseType="BINARY"/>
        </payload>
        <subPayload domain="F63">
            <field domainNo="0" name="f63f0" fixed="true" length="3" remark="bitmap" className="BitMap" parseType="BINARY"/>
            <field domainNo="1" name="f63f1" fixed="true" length="2" remark="Network Identification Code" className="String" parseType="BCD"/>
            <field domainNo="2" name="f63f2" fixed="true" length="2" remark="Time (Preauth Time Limit)" className="String" parseType="BCD"/>
            <field domainNo="3" name="f63f3" fixed="true" length="2" remark="Message Reason Code" className="String" parseType="BCD"/>
            <field domainNo="4" name="f63f4" fixed="true" length="2" remark="STIP/Switch Reason Code" className="String" parseType="EBCDIC"/>
            <field domainNo="6" name="f63f6" fixed="true" length="7" remark="Chargeback Reduction/BASE II Flags" className="String" parseType="EBCDIC"/>
            <field domainNo="8" name="f63f8" fixed="true" length="4" remark="Visa Acquirer's Business ID" className="String" parseType="BCD"/>
            <field domainNo="9" name="f63f9" fixed="true" length="14" remark="Fraud Data" existSubdomain="true" subdomainType="FIXED"/>
        </subPayload>
        <subPayload domain="F63_F9">
            <field domainNo="1" name="f63f9f1" fixed="true" length="1" remark="Fraud Type" className="String" parseType="EBCDIC"/>
            <field domainNo="2" name="f63f9f2" fixed="true" length="1" remark="Fraud Notification Code" className="String" parseType="EBCDIC"/>
            <field domainNo="3" name="f63f9f3" fixed="true" length="2" remark="Fraud Type Classification cation" className="String" parseType="EBCDIC"/>
            <field domainNo="4" name="f63f9f4" fixed="true" length="1" remark="Fraud Reporting Entity" className="String" parseType="EBCDIC"/>
            <field domainNo="5" name="f63f9f5" fixed="true" length="9" remark="Reserved" className="String" parseType="EBCDIC"/>
        </subPayload>
    </message>
</alatka-messages>

=== goGetSomeFries/alatka-messages/alatka-messages-core/src/test/resources/mastercard.common.iso.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="iso" group="mastercard" code="common" remark="master 8583报文">
        <payload>
            <field domainNo="0" name="messageType" fixed="true" length="4" remark="报文类型" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="1" name="bitMap" fixed="false" length="16" remark="位图" clazz="java.util.HashMap" parseType="BINARY"/>
            <field domainNo="2" name="pan" fixed="false" length="2" maxLength="19" remark="主账号" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="3" name="processingCode" fixed="true" length="6" remark="交易处理码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="4" name="amtTrans" fixed="true" length="12" remark="交易金额" clazz="java.math.BigDecimal" parseType="EBCDIC"/>
            <field domainNo="5" name="amtSettlmt" fixed="true" length="12" remark="清算金额" clazz="java.math.BigDecimal" parseType="EBCDIC"/>
            <field domainNo="6" name="amtCdhldrBil" fixed="true" length="12" remark="持卡人扣账金额" clazz="java.math.BigDecimal" parseType="EBCDIC"/>
            <field domainNo="7" name="transmsnDateTime" fixed="true" length="10" remark="交易传输时间" clazz="java.time.LocalDateTime" pattern="MMddHHmmss" parseType="EBCDIC"/>
            <field domainNo="9" name="convRateSettlmt" fixed="true" length="8" remark="清算汇率" clazz="java.lang.Integer" parseType="EBCDIC"/>
            <field domainNo="10" name="convRateCdhldrBil" fixed="true" length="8" remark="持卡人扣账汇率" clazz="java.lang.Integer" parseType="EBCDIC"/>
            <field domainNo="11" name="sysTraceAuditNum" fixed="true" length="6" remark="系统跟踪号" clazz="java.lang.Integer" parseType="EBCDIC"/>
            <field domainNo="12" name="timeLocalTrans" fixed="true" length="6" remark="受卡方所在地时间" clazz="java.time.LocalTime" pattern="HHmmss" parseType="EBCDIC"/>
            <field domainNo="13" name="dateLocalTrans" fixed="true" length="4" remark="受卡方所在地日期" clazz="java.time.MonthDay" pattern="MMdd" parseType="EBCDIC"/>
            <field domainNo="14" name="dateExpr" fixed="true" length="4" remark="卡有效期" clazz="java.time.YearMonth" pattern="yyMM" parseType="EBCDIC"/>
            <field domainNo="15" name="dateSettlmt" fixed="true" length="4" remark="清算日期" clazz="java.time.MonthDay" pattern="MMdd" parseType="EBCDIC"/>
            <field domainNo="16" name="dateConv" fixed="true" length="4" remark="兑换日期" clazz="java.time.MonthDay" pattern="MMdd" parseType="EBCDIC"/>
            <field domainNo="17" name="dateCapture" fixed="true" length="4" remark="date Capture" clazz="java.time.MonthDay" pattern="MMdd" parseType="EBCDIC"/>
            <field domainNo="18" name="mchntType" fixed="true" length="4" remark="商户类型" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="19" name="mchntCntryCode" fixed="true" length="3" remark="商户国家代码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="22" name="posEntryModeCode" fixed="true" length="3" remark="服务点输入方式码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="23" name="cardSeqId" fixed="true" length="3" remark="卡序列号" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="25" name="posCondCode" fixed="true" length="2" remark="服务点条件码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="26" name="posPinCaptrCode" fixed="true" length="2" remark="服务点PIN获取码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="28" name="amtTransFee" fixed="true" length="9" remark="交易费" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="32" name="acqInstIdCode" fixed="false" length="2" maxLength="11" remark="代理机构标识码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="33" name="fwdInstIdCode" fixed="false" length="2" maxLength="11" remark="发送机构标识码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="35" name="tracK2Data" fixed="false" length="2" maxLength="37" remark="第二磁道数据" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="36" name="tracK3Data" fixed="false" length="3" maxLength="104" remark="第三磁道数据" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="37" name="retrivlRefNum" fixed="true" length="12" remark="检索参考号" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="38" name="authrIdResp" fixed="true" length="6" remark="授权标识应答码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="39" name="respCode" fixed="true" length="2" remark="应答码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="41" name="cardAccptrTermnlId" fixed="true" length="8" remark="受卡机终端标识码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="42" name="cardAccptrId" fixed="true" length="15" remark="受卡方标识码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="43" name="cardAccptrNameLoc" fixed="true" length="40" remark="受卡方名称地址" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="44" name="addtnlRespCode" fixed="false" length="2" maxLength="25" remark="附加响应数据" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="45" name="tracK1Data" fixed="false" length="2" maxLength="76" remark="第一磁道数据" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="48" name="addtnlDataPrivate" fixed="false" length="3" maxLength="512" remark="附加数据——私有" existSubdomain="true" subdomainType="FIXED" lenParseType="EBCDIC"/>
            <field domainNo="49" name="currcyCodeTrans" fixed="true" length="3" remark="交易货币代码" className="String" parseType="EBCDIC"/>
            <field domainNo="61" name="chAuthInfo" fixed="false" length="3" maxLength="200" remark="持卡人身份认证信息" existSubdomain="true" subdomainType="FIXED" lenParseType="EBCDIC"/>
        </payload>
        <subPayload domain="F48">
            <field domainNo="1" name="riskCode" fixed="true" length="1" remark="风险原因代码" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="2" name="riskLevel" fixed="false" length="-1" remark="风险等级" existSubdomain="true" subdomainType="ULV2"/>
        </subPayload>
        <subPayload domain="F48_F2" usage="42">
            <field domainNo="1" name="f48f2f1" fixed="true" length="7" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
        </subPayload>
        <subPayload domain="F48_F2" usage="77">
            <field domainNo="1" name="f48f2f1" fixed="true" length="3" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
        </subPayload>
        <subPayload domain="F61">
            <field domainNo="1" name="f61f1" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="2" name="f61f2" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="3" name="f61f3" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="4" name="f61f4" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="5" name="f61f5" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="6" name="f61f6" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="7" name="f61f7" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="8" name="f61f8" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="9" name="f61f9" fixed="true" length="1" remark="test" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="10" name="f61f10" fixed="true" length="1" remark="Use" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="11" name="f61f11" fixed="true" length="1" remark="Use" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="12" name="f61f12" fixed="true" length="2" remark="Use" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="13" name="f61f13" fixed="true" length="3" remark="Use" clazz="java.lang.String" parseType="EBCDIC"/>
            <field domainNo="14" name="f61f14" fixed="true" length="10" remark="Use" clazz="java.lang.String" parseType="EBCDIC"/>
        </subPayload>
    </message>
</alatka-messages>

=== goGetSomeFries/alatka-messages/alatka-messages-core/src/test/resources/9001.4118.fixed.xml
<?xml version="1.0" encoding="UTF-8" ?>
<alatka-messages xmlns="http://messages.alatka.com"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://messages.alatka.com alatka-messages.xsd">
    <message type="fixed" group="9001" code="4118" remark="内容交易">
        <request>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" className="String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" className="String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" className="String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" className="String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" className="String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" className="String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" className="Integer"/>
            <field domainNo="8" name="option" length="8" remark="标志位" className="String"/>
            <field domainNo="9" name="custNbr" length="19" remark="证件号码" className="String"/>
            <field domainNo="10" name="cardNbr" length="19" remark="卡号" className="String"/>
            <field domainNo="11" name="tagType" length="5" remark="标签类型" className="String"/>
            <field domainNo="12" name="tagCode" length="4" remark="标签代码" className="String"/>
            <field domainNo="13" name="tagInfo" length="20" remark="标签内容" className="String"/>
            <field domainNo="14" name="resvd" length="500" remark="保留域" className="String"/>
        </request>
        <response>
            <field domainNo="1" name="trxType" length="4" remark="交易代码" className="String"/>
            <field domainNo="2" name="retCode" length="6" remark="响应码" className="String"/>
            <field domainNo="3" name="bnkNbr" length="4" remark="银行代号" className="String"/>
            <field domainNo="4" name="source" length="2" remark="交易来源" className="String"/>
            <field domainNo="5" name="brnNo" length="6" remark="网点代号" className="String"/>
            <field domainNo="6" name="opeNo" length="6" remark="操作员号" className="String"/>
            <field domainNo="7" name="seqNo" length="6" remark="流水号" className="Integer"/>
            <field domainNo="8" name="option" length="8" remark="标志位" className="String"/>
            <field domainNo="9" name="custNbr" length="19" remark="证件号码" className="String"/>
            <field domainNo="10" name="cardNbr" length="19" remark="卡号" className="String"/>
            <field domainNo="11" name="tagType" length="5" remark="标签类型" className="String"/>
            <field domainNo="12" name="tagCode" length="4" remark="标签代码" className="String"/>
            <field domainNo="13" name="tagInfo" length="20" remark="标签内容" className="String"/>
            <field domainNo="14" name="resvd" length="500" remark="保留域" className="String"/>
        </response>
    </message>
</alatka-messages>
